### ISSUE TITLE
how to create VARIADIC "any" function

### ISSUE THREAD

**Issue by ibotty** [pgcentralfoundation/pgrx#1505] opened 2024-01-31 21:21 UTC
For the sake of argument, let's try to recreate `jsonb_build_array` which takes a variable number of parameters of possibly different types.

I tried using
```
#[pg_extern]
pub fn test_variadic(a: VariadicArray<AnyElement>) -> i64 {
  42
}
```
but that fails when creating the extension with
```
ERROR:  type anyelement[] does not exist
```

**Comment by workingjubilee** [comment] 2024-01-31 22:07
VariadicArray still corresponds to ArrayType, in effect, and you cannot have non-homogenous ArrayTypes. A JSON "array" requires a truly variadic type. I honestly am not sure if VariadicArray has any major purpose except as a backwards compatibility shim for certain cases in an existing extension.

I believe the main way you do this, currently, is by accepting `pg_sys::FunctionCallInfo` as an argument and doing the unpacking yourself, unfortunately, and writing the necessary SQL.

**Comment by ibotty** [comment] 2024-01-31 22:17
Thank you for your quick reply!

Can you go into a little more detail?  Or point me to some code that does something similar?  What kind of SQL would I have to write?

**Comment by workingjubilee** [comment] 2024-01-31 23:05
@ibotty

Start with this:
```rust
#[pg_extern(sql = r#"
    CREATE OR REPLACE FUNCTION "accepts_variadic_any"(VARIADIC "any") RETURNS bool
    STRICT
    LANGUAGE c /* Rust */
    AS '@MODULE_PATHNAME@', '@FUNCTION_NAME@';
"#)]
fn accepts_variadic_any(var_args: pg_sys::FunctionCallInfo) -> bool {
    true
}
```

Then use `pg_getarg`.

You can coax pgrx into accepting as many initial arguments as you want, and it will handle the Postgres V1 Call ABI's argument-unpacking for the first set, but then you have to call `pg_getarg` for the remainder and manually reason about things.

```rust
#[pg_extern(sql = r#"
    CREATE OR REPLACE FUNCTION "accepts_variadic_any"(text, int4, VARIADIC "any") RETURNS bool
    STRICT
    LANGUAGE c /* Rust */
    AS '@MODULE_PATHNAME@', '@FUNCTION_NAME@';
"#)]
fn trailing_variadic_any(some_text: String, some_int: i32, var_args: pg_sys::FunctionCallInfo) -> bool {
    true
}
```

**Comment by workingjubilee** [comment] 2024-02-01 02:18
I hope that answers your question, and thank you for asking! It helps motivate another piece of work. I am arbitrarily deciding this is secretly a duplicate of #1428, even if no one realized it at the time.

**Closed as not planned** 2024-02-01 02:19 UTC

**Comment by ibotty** [comment] 2024-02-11 10:55
Whenever I have time, I'll try to cook up an example to be included with pgrx' examples.
