### ISSUE TITLE
Invalid or unknown abi 16 for function "_ZGVnN4vv_atan2f"

### ISSUE THREAD

**Issue by chaosong** [pgcentralfoundation/pgrx#1834] opened 2024-08-30 10:32 UTC
OS: ubuntu24.04
ARCH: arm64
PostgreSQL: 16.3

```
Compiling pgrx-pg-sys v0.10.2          
error: failed to run custom build command for `pgrx-pg-sys v0.10.2`                                                                                                                           
Caused by:                                                                                                                       process didn't exit successfully: `/opt/pg/src/tmp/pg_tiktoken/target/release/build/pgrx-pg-sys-6273f32d4142b301/build-script
-build` (exit status: 101)                                                                                                      
--- stdout                                                   
  cargo:rerun-if-env-changed=PGRX_BUILD_VERBOSE    
......                                                                              
  cargo:rerun-if-env-changed=PGRX_BINDGEN_NO_DETECT_INCLUDES                                                                                                                                  
  --- stderr                                                                                                                     build_paths=BuildPaths { manifest_dir: "/home/postgres/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pgrx-pg-sys-0.10.
2", out_dir: "/opt/pg/src/tmp/pg_tiktoken/target/release/build/pgrx-pg-sys-928137f5726e799c/out", src_dir: "/home/postgres/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pgrx-pg-sys-0.10.2/src/include", shim_src: "/home/postgres/.cargo/registry/src
/index.crates.io-6f17d22bba15001f/pgrx-pg-sys-0.10.2/cshim", shim_dst: "/opt/pg/src/tmp/pg_tiktoken/target/release/build/pgrx-pg-sys-928137f5726e799c/out/cshim" }     
  Generating bindings for pg16       

thread '<unnamed>' panicked at /home/postgres/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.68.1/codegen/mod.rs:4195:17:
Invalid or unknown abi 16 for function "_ZGVnN4vv_atan2f" (Function { name: "_ZGVnN4vv_atan2f", mangled_name: Some("_ZGVnN4vv_atan2f"), link_name: None, signature: TypeId(ItemId(25034)), kind: Function, linkage: External })
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  thread 'main' panicked at /home/postgres/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pgrx-pg-sys-0.10.2/build.rs:196:41:
```

**Comment by usamoi** [comment] 2024-08-31 09:49
Duplicate of #1429 and #1799.

**Closed as not planned** 2024-09-02 19:35 UTC
